package(
    default_visibility = ["//tensorflow/lite/micro/signal:__subpackages__"],
    licenses = ["notice"],
)

cc_library(
    name = "window",
    srcs = ["window.cc"],
    hdrs = ["window.h"],
)